### ISSUE TITLE
Comptabilisation des points - confusion case à cocher (carrée) et question à choix multiple (ronde)

### ISSUE THREAD

**Issue by noteplume** [kidoju/Kidoju-Feedback#10]
Bonjour,
J'ai créé deux pages. Lorsque je joue et que je réponds faux à la première question et juste à la deuxième, le résultat affiche 25% de juste alors que ça devrait être 50 %.
Merci

**Comment by noteplume** [comment]
De même avec une troisième page créée, le résultat n'est que de 60 % pour toutes les réponses justes

**Comment by jlchereau** [comment]
Je vois 5 questions sur 3 pages et toutent valent 1 point: les résulats seront donc 0%, 20%, 40%, 60%, 80% ou 100%.

Chaque case à cocher est une question (vrai/faux) avec son propre score. Les checkboxes sont cumulatives. Cochez toutes les cases pour avoir la totalité des points.

Pour avoir un choix alternatif, il faut utiliser l'ouil Question à Choix Multiple (QUIZ) et demander le mode radio (forme ronde au lieu de carrée). Pour plus d'information, voir #11.

![image](https://cloud.githubusercontent.com/assets/2556751/13878287/2d2a176e-ed08-11e5-91ec-cbdfe8bf6a6a.png)

**Comment by jlchereau** [comment]
Par ailleurs les pourcentages sont déterminès par le nombre total de points de type **Succès** donnés dans la logique de test, sachant qu'on peut donner des points négatifs pour **Echec**.

![image](https://cloud.githubusercontent.com/assets/2556751/13878339/8e29d13a-ed08-11e5-8ec3-a391b6b7f1b4.png)

**Comment by noteplume** [comment]
Ok bien compris. Merci

**Comment by LouiseCNS** [comment]
Bonjour,
De la même manière que pour les points à relier, il n'est pas possible de changer le nom de la valeur (val_9987 par ex). Cela rend la lecture des corrections particulièrement compliquée puisque le logiciel affiche le nom des valeurs en correction. Même si on met le nom de la proposition en description, la lecture de la correction reste assez difficile.
Merci d'avance.

**Comment by jlchereau** [comment]
C'est corrigé: voir #16 et #25.
