### ISSUE TITLE
Comment utiliser les questions à réponse ouverte (les boites de texte)?

### ISSUE THREAD

**Issue by jlchereau** [kidoju/Kidoju-Feedback#12]
> L'outil pour poser une question ouverte est la boite de texte (TextBox)
### Ajouter une textbox

Après vous être identifié et avoir sélectionné votre projet à éditer comme expliqué en #2, créez une nouvelle page comme expliqué en #3.

Sélectionnez l’outil Boite de Texte (TexBox) dans la boite à outils du panneau de droite et cliquez sur la surface d’édition dans le panneau central.

![image](https://cloud.githubusercontent.com/assets/2556751/13880541/867898fc-ed14-11e5-91c6-34aab16b4d12.png)
### Désigner la solution et donner les points

On désigne la bonne solution dans le champ **Solution** de la logique de test comme ci-dessous.

Ensuite on donne les points que l'utilisateur recevra en cas de **Succès**, d'**Echec** et d'**Ommission** (pas de réponse).

Accessoirement, il est bon de donner la **Description** (courte!) qui apparait dans le rapport de correction pour cette question.

![image](https://cloud.githubusercontent.com/assets/2556751/13880629/08c6fbb4-ed15-11e5-87b1-fe35a860cbca.png)
### Améliorer la validation

Les questions ouvertes posent une problématique complexe de validation.

Dans l'exemple de la copie d'écran ci-dessus, nous avons désigné **Henri IV** comme bonne réponse, mais ne devrions-nous pas accepter aussi **henri iv**, **Henri 4** ou encore **Henri de Navarre**?

Nous mettons pour cela à dispositions plusieurs algorithmes de validation:
- **equal** est l'identité parfaite, soit _Henri IV_ dans note example.
- **ignoreCaseEqual** ne distingue pas les majuscules et minuscules, do sorte que _henri iv_ serait aussi valide.
- **ignoreDiacriticsEqual** ne distingue pas les majuscules et minuscules et les accents, de sorte que _Héñrì IV_ serait valide.
- **match** fait une comparaison de type expression régulière (voir #13)
- **ignoreCaseMatch** fait une comparaison de type expression régulière sans distinguer les majuscules et minuscules
- **soundex** et **metaphone** sont des algrorithmes phonétiques qui marchent très bien en  anglais mais moins bien dans les autres langues. [Soundex](https://en.wikipedia.org/wiki/Soundex) est plus tolérant (moins précis) que [Métaphone](https://en.wikipedia.org/wiki/Metaphone). Ces algorithmes permettent d'être très tolérants avec les fautes d'orthographes sans se soucier des multiples variations possibles.

Dans l'exemple ci-dessus, je choisirais l'algorithme **ignoreCaseMatch** et je renseignerais le champ **Solution** avec une expression régulière de la forme `^henri\s+(iv|4|de\s+navarre)$` dans laquelle:
- `^` désigne le début de la réponse (si on omet `^` on valide une réponse qui se termine par l'expression), 
- `\s+` signifie au moins 1 espace (dans les expressions régulières, les caractères spéciaux sont préfixés par `\`, `*` signifie une répétition de 0 ou plus, `+` signifie une répétition de 1 ou plus, et `?` est le suffixe d'un caractère optionnel).
- `(a|b|c)` signifie `a` ou `b` ou `c`, et
- `$` désigne la fin de la réponse (si on omet `$` on valide une réponse qui commence par l'expression et si on omet à la fois `^` et `$` on valide une réponse qui contient l'expression).

Pour en savoir plus sur les expressions régulières, voir #13.

Pour des validations plus sophistiquées, il est encore possible d'écrire sa fonction de comparaison en JavaScript en cliquant sur le bouton `...` du champ **Validation**:

![image](https://cloud.githubusercontent.com/assets/2556751/13881015/0dd8081c-ed17-11e5-9180-c5d91e8381c2.png)

**Comment by jlchereau** [comment]
`a=b`

**Comment by LouiseCNS** [comment]
Bonjour,
L'outil  ignoreDiacriticsEqual ne marche pas : lorsque l'on fait un test avec ce paramètres dans une textbox, le message d'erreur "il y'a une erreur dans le calcul du score" s'affiche.
Ce problème n'existe pas avec ignoreCaseEqual.
Merci d'avance !

**Comment by jlchereau** [comment]
J'arrive à reproduire le bug. Ce sera corrigé dans la prochaine version.

**Comment by jlchereau** [comment]
C'est corrigé dans la version v0.1.8
