### ISSUE TITLE
Comment utiliser les connecteurs?

### ISSUE THREAD

**Issue by jlchereau** [kidoju/Kidoju-Feedback#16]
> Les connecteurs dans les tests Kidoju offrent la possibilité de lier deux concepts, dans le cas plus fréquent une image (ou une partie d'une image) à une légende.
### Exemple

Imaginez par exemple que l'on souhaite demander à l'utilisateur de lier les parties du coeur humain aux légendes comme dans la représentation ci-dessous:

![image](https://cloud.githubusercontent.com/assets/2556751/14408794/274e9596-fefa-11e5-92d0-cb54b90d0eb8.png)
### Ajout

Il vous faut d'abord aller dans l'éditeur de Kidoju suivant les instructions de #1 ou #2. Ensuite cliquez le bouton **Connnecteur** dans la boite à outils du panneau de droite et cliquez la surface d'édition dans le panneau central.

_Note: pour ajouter l'image, voir #7 et pour ajouter les labels voir #5_.

![image](https://cloud.githubusercontent.com/assets/2556751/14408716/f8225f16-fef7-11e5-93cb-be03cd3f845f.png)
### Couleur

Dans les attributs d'affichage du panneau de droite, modifiez le champ **Couleur**. 

![image](https://cloud.githubusercontent.com/assets/2556751/14408722/19c06168-fef8-11e5-8faa-dd2b588a4e41.png)
### Logique de test

La logique de test des connecteurs consiste à faire correspondre les solutions sur le connecteur source (ici, sur l'image) et le connecteur destination (ici, à coté du texte). Les connecteurs sont symétriques: l'origine (source) et la destination (cible) du lien sont inversibles sans que cela affecte le résultat.

![image](https://cloud.githubusercontent.com/assets/2556751/14408791/076f62c8-fefa-11e5-881b-3a9b33e9c344.png)

**Attention: Seul un couple de connecteurs de la même page peut avoir la même solution. Si un autre composant de la mème page devait avoir une solution identique, les résultats seraient faussés.**
### Ordonnez vos connecteurs

La surface de dessin des lignes de connection se trouve juste derrière le connecteur le plus en arrière plan. Il est important que vos connecteurs se situent:
- en avant-plan par rapport aux **images** et **labels** pour que les lignes de connection soient dessinées au dessus. Assurez-vous dans l'explorateur que les connecteurs se trouvent tous plus bas que les images dans la liste.
- en arrière plan par rapport aux composants de saisie comme les **Quiz**, **Textboxes** et **CheckBoxes** que vous pouvez avoir mis sur la même page et qui autrement ne seront pas accessibles à cause de la surface de dessin des liens qui sera en avant-plan et qui capturera donc le focus. Assurez -vous dans l'explorateur que les composants interactifs se trouvent tous plus bas que les connecteurs dans la liste.

![image](https://cloud.githubusercontent.com/assets/2556751/14408792/14692450-fefa-11e5-8796-1e5f69cca166.png)

**Attention! il n'est pas recommandé de mettre des connecteurs et des zones de dépôt (DropZone) sur la même page. C'est possible mais complexe à ordonner correctement dans l'explorateur.**

**Comment by LouiseCNS** [comment]
Bonjour, il n'est pas possible de changer le nom de la cible. Cela rend la lecture des corrections particulièrement compliquée puisque le logiciel affiche le nom des cibles en correction. 
Il serait plus simple de pouvoir renommer les cibles (au lieu d'avoir à renommer systématiquement la description). Merci d'avance.

**Comment by jlchereau** [comment]
Pour des raisons techniques les noms de cibles doivent être uniques et ne comporter que les caractères a-z 0-9 et _ (caractères autorisés pour les variables Javascript). Ce ne sera donc pas satisfaisant dans de multiples langues.

Il fait réfléchir à d'autres moyens d'améliorer l'affichage de la correction en notant qu'en cliquant un élément de la correction, on va directement sur la page ou l'on obtient les explications.

**Comment by jlchereau** [comment]
Les connecteurs sont modifiés et les résultats s'affichent dorénavant sans val_####:

![image](https://cloud.githubusercontent.com/assets/2556751/14408799/46d68342-fefa-11e5-847c-a78f7537b539.png)

**Comment by LouiseCNS** [comment]
Bonjour, 

Je n'arrive pas à utiliser les connecteurs : 
![capture d ecran 2016-04-17 a 16 48 19](https://cloud.githubusercontent.com/assets/18120149/14587920/50acee2a-04bc-11e6-9b56-697fa9a527fb.png)

Est-ce la bonne façon ? Faut-il mettre les valeurs ? 

Merci pour votre réponse,

Louise

**Comment by jlchereau** [comment]
Je ne comprends pas ce qui ne fonctionne pas.

En mode "Edition" (dans l'éditeur) vous ne pouvez pas expérimenter les connexions (traits) entre deux connecteurs. Il faut Jouer le test pour pouvoir connecter. Est-ce votre problème?

Vous pouvez tester l'exemple ci-dessus à l'adresse https://www.kidoju.com/en/x/570cc7f46d1dd91900729417/570cc7f56d1dd91900729418#/9

**Comment by LouiseCNS** [comment]
Bonjour,
Je me suis mal exprimée : une fois le test parametré comme montré sur la capture d'écran
 (pour les deux boutons de façon réciproque càd pour le bouton de gauche :
description : thomas edison
solution : electricité
et pour le bouton de droite :
description : electricité
solution : Thomas Edison)

, le quizz ne prend pas en compte la bonne réponse : 
![capture d ecran 2016-04-17 a 23 20 29](https://cloud.githubusercontent.com/assets/18120149/14590100/0afe48b0-04f3-11e6-9d86-d9f51a0bdbaa.png)
Pourriez-vous nous expliquer le problème de rédaction du test logique dans ce cas ?
Faut-il ne coder la solution que sur un seul des deux boutons ?

Merci d'avance !

**Comment by jlchereau** [comment]
Dans la précédente version, la solution consistait effectivement à désigner la cible.

Suite à la modification que vous avez sollicitée pour éviter l'affichage des noms techniques en "val_" dans les résultat de recherche, il faut maintenant que la solution soit la même sur les deux connecteurs (c'est expliqué dans la doc ci-dessus):
- Elecricité === Electricité, ou
- Thomas Edison === Thomas Edison, ou
- T. Edison (Electricité) === T. Edison (Electricité).

Dans votre paramétrage, Thomas Edison !== Electricité et le résultat est FAUX.

**Comment by jlchereau** [comment]
La correction pour les connecteurs qui sont très graphiques n'est pas facile à représenter clairement dans une liste abrégée. C'est pour cela que les éléments de la liste renvoient à la page où l'utilisateur peut trouver des explications.

Je vous rappelle à cette occasion que vous pouvez aussi afficher les explications sous la forme d'images comme dans l'exemple ci-dessous:

![image](https://cloud.githubusercontent.com/assets/2556751/14601403/cf61a7a4-0559-11e6-8fae-397c27c8d1ea.png)

Dans ce cas, les explications sont:

```
![Body Parts](https://upload.wikimedia.org/wikipedia/commons/6/6a/Human_body_features-en.svg)

For more information, please visit [Wikipedia](https://en.wikipedia.org/wiki/Human_body)
```

Pour plus d'information voir #14
