### ISSUE TITLE
site anglais et français

### ISSUE THREAD

**Issue by noteplume** [kidoju/Kidoju-Feedback#19]
Un test rédigé et publié sur le site français est-il disponible sur le site anglais et vice versa?

**Comment by jlchereau** [comment]
NON, les deux sont totalement séparés.

Il y a plusieurs raisons pour cela, notamment:
1. La sémantique des recherches pleint texte n'est pas la même. En francais, certains mots non significatifs comme `le`, `la`, `un`, `de`, etc. sont exclus des index. En anglais, c'est `a`, `an`, `the`, etc.
2. L'affichage est aussi localisé pour les nombres et les dates. Par exemple le séparateur décimal en francais est la virgule et en anglais, c'est le point.

On ne peut pas mixer les deux sans faire n'importe quoi.
