### ISSUE TITLE
Duplication de test

### ISSUE THREAD

**Issue by noteplume** [kidoju/Kidoju-Feedback#20]
Il serait utile de pouvoir dupliquer un test qui pourrait servir ainsi de trame pour un nouveau test. Est-ce prévu dans une prochaine version du site? Merci

**Comment by jlchereau** [comment]
La priorité de cette fonctionalité est actuellement basse car:
1. Je ne maitrise pas les implications juridiques (copyright,etc.);
2. Je crains la multiplication des tests identiques par les utilisateurs qui "essayent";
3. Sur le plan technique, cela pose un probleme d'atomicité transactionelle quand on duplique les assets (images, fichiers audio et video): que faire si la copie échoue entre la n-ème et la n+1-ème image dès lors que la plateforme Amazon ne garantit pas les copies dans une même transaction? C'est pas trivial.

Elle n'est donc pas prévue dans la roadmap des 3 prochains mois.

**Comment by LouiseCNS** [comment]
Bonjour, ce problème pourrait-il être surmonté en donnant la possibilité "d'enregistrer sous" le quizz, puis de le reuploader sur le site ? Merci d'avance.

**Comment by LouiseCNS** [comment]
De même, serait-il possible de dupliquer une slide au sein d'un quizz ? Ou cela pose-t-il les mêmes problèmes que précédement ?

**Comment by jlchereau** [comment]
Import/export = même complexité que la duplication de test à fortiori d'une langue vers l'autre.

Dupliquer une slide est facile à faire et tout à fait envisageable à court terme.

**Comment by LouiseCNS** [comment]
Bonjour, serait-il du coup possible d'ajouter rapidement l'option de duplication des slides ? Ceci aiderait beaucoup pour la création des quizz !
Merci d'avance !

**Comment by jlchereau** [comment]
Ce sera fait dans le courant de la semaine prochaine.

**Comment by jlchereau** [comment]
Je viens de faire une mise à jour le 04/04/2016 à 18h25 GMT avec la version v4.4.10 de mongoose. Kidoju est maintenant en version v0.0.12.

La mise a jour contient la duplication de page:

![image](https://cloud.githubusercontent.com/assets/2556751/14255321/6d18fdaa-fa8b-11e5-81ce-8bfdde5a3898.png)

**Attention! la duplication de page ne duplique que les attributs d'affichage des composants, mais pas la logique de test.**

**Comment by LouiseCNS** [comment]
Bonjour, 
Je me permets de vous relancer sur cette possibilité : serait-il possible de pouvoir dupliquer un test uniquement de la plateforme anglaise à la plateforme française (et inversement), au moins transitoirement ?

**Comment by jlchereau** [comment]
Il y a 5 à 10 jours de développement pour une telle fonctionnalité car il faut dupliquer les images, les vidéos, et autres fichiers qui sont stockés dans Amazon S3 et pas dans la base de données et développer un mécanisme d'intégrité transactionnelle qui (1) s'assure de la reprise sur incident quand la copie d'un fichier initie une erreur, et (2) annule toutes les copies dans S3 si l'ensemble ne peut pas être copié (base de données non disponible, etc.).

On a une roadmap avec des fonctionnalités qui doivent être livrées pour avoir l'application mobile cet été. Ce n'est pas quelque chose qui s'insère facilement.

Il y a peut-être la possibilité de faire tourner un script sur la base de données pour dupliquer une liste de tests sans dupliquer les fichiers (images, etc.) que vous auriez à télécharger manuellement de sorte que vous géreriez l'intégrité.

C'est une manipulation dangereuse. Il n'est donc pas question de le faire sur la base de données en LIVE, ce qui suppose d'arrêter le site pour faire un backup, modifier la base de données, vérifier et relancer le site soit avec le backup soit avec la mise à jour. Potentiellement, ce n’est pas certain de réussir du premier coup.

Il y en a pour au moins 2 jours (préparation + exécution). C'est un travail pénible et on ne peut pas tout arrêter pour le faire demain. Il va falloir me donner une bonne raison de le planifier.
