### ISSUE TITLE
Bonne réponse comptée fausse

### ISSUE THREAD

**Issue by npkidoju** [kidoju/Kidoju-Feedback#21]
2 problèmes:
-ds le test de Pierre sur l'Europe, question avec les flèches, après avoir "soumis", les réponses ne s'affichent que sous formes de valeurs, on ne sait donc pas si on a bon ou faux et surtout quelle est la bonne réponse
-ds le test d'Alexandre sur le calcul des coûts, questions 8 et 10: j'ai donné la bonne réponse mais il me la compte fausse... à voir pourquoi, question d'espace ou autre?

1point: ds le test d'Alexandre sur le calcul des coûts, question 3: peut- on considérer plusieurs bonnes réponses, et donc en général pourra-t-il y avoir plusieurs bonnes réponses ou pas à des questions?

**Comment by jlchereau** [comment]
Alexandre a 4 tests publics et aucun n'est titré **calcul des coûts**. Ca prend trop de temps d'analyser tous les tests pour tenter de retrouver les questions.

Pouvez-vous me donner les liens sur les pages en question, par exemple: [https://www.kidoju.com/fr/x/56f7f76bd188a51a00909551/56f7f76bd188a51a00909552#/6](https://www.kidoju.com/fr/x/56f7f76bd188a51a00909551/56f7f76bd188a51a00909552#/6)?

Merci

**Comment by noteplume** [comment]
Pour Alexandre, j'ai trouvé c'est un point qui manquait dans la réponse ("logique de test"- solution)

**Comment by noteplume** [comment]
pour les fameuses réponses avec des val...
un exemple de grille de réponses https://www.kidoju.com/fr/x/56ff91f38e3e2f1d0072d79b/56ff91f48e3e2f1d0072d79c#/report/memory

**Comment by jlchereau** [comment]
Est-ce relatif aux connecteurs? Dans ce cas, c'est maintenant résolu. Merci de confirmer.
