### ISSUE TITLE
problemes sur le site 2 et 3 avril

### ISSUE THREAD

**Issue by noteplume** [kidoju/Kidoju-Feedback#22]
Bonjour,
Lenteur du service, incapacité à se connecter, tentative de jouer à un jeu (sur les romains, session de Pierre) mais arrivé à la dernière question, cliquer sur "soumettre" ne donne rien. Pas possible d'accéder à la page de liste des quiz sur la session de Pierre.
Google Chrome

**Comment by LouiseCNS** [comment]
Nous rencontrons le même type de problème  : "Il y a un problème sur le site kidoju : je ne peux pas avancer car ma session ne reste pas connectée plus de quelques minutes... Au début je ne comprenais pas, je cliquais sur enregistrer, ça me disait que c'était bien enregistré mais au bout d'un moment ça enregistrait plus, je pouvais pas charger d'images.... Je retournais à la liste de mes quizz et là je me rendais compte que je n'étais plus connectée, j'étais obligée de me reconnecter au site et quand j'allais voir mon quizz, rien de ce que j'avais fait n'avait été enregistré.... "

**Comment by jlchereau** [comment]
Sous toutes réserves, il semble que ce soit un problème avec **mongoose**, un composant de Kidoju fait par un tiers. Il semble que ce soit résolu par la version 4.4.10. Je ferai donc une mise à jour du système ce soir.

Pour plus d'information, voir https://github.com/Automattic/mongoose/issues/3752#issuecomment-205190946.

**Comment by noteplume** [comment]
de ce que je constate c'est quand on quitte et que l'on veut revenir sur le site en ouvrant une nouvelle session qu'un blocage s'effectue

**Comment by jlchereau** [comment]
Il n'y a qu'un message d'erreur dans les logs de Kidoju et c'est toujours le même. Voir Automattic/mongoose#3752 (comment).

Si l'utilisateur n'est plus identifié, il ne peut plus enregistrer. C'est juste une conséquence.

Je viens de faire une mise à jour le 04/04/2016 à 18h25 GMT avec la version v4.4.10 de **mongoose**. Kidoju est maintenant en version v0.0.12.

**Comment by jlchereau** [comment]
Sous réserve de votre confirmation, la mise à jour d'hier semble avoir resolu le problème d'identification: je ne peux plus reproduire le problème.
