### ISSUE TITLE
transfert sur l'interface anglaise

### ISSUE THREAD

**Issue by npkidoju** [kidoju/Kidoju-Feedback#24]
Quand des tests ont été fait sur la partie française du site et que ils sont en fait destinés à la partie anglaise, comment faire pour les transférer sans tout perdre et tout recommencer ?

**Comment by jlchereau** [comment]
Il n'y a pas de moyen via l'interface. Voir #19.

Par contre, **pour un nombre limité de tests** et si vous me donnez les URLs (copiez l'adresse de l'éditeur avec les deux identifiants à 24 chiffres), je peux faire le transfert en database.

**Comment by LouiseCNS** [comment]
Merci pour cette réponse !
Les quizz à transférer sont : de l'anglais vers le français 
- https://www.kidoju.com/en/s/56fe62cdd188a51a00909814?bypass=true
- https://www.kidoju.com/en/s/56ffc2018e3e2f1d0072d7d6?bypass=true
- https://www.kidoju.com/en/s/56ffa4ba8e3e2f1d0072d7b0?bypass=true
- https://www.kidoju.com/en/s/56fe6bb48e3e2f1d0072d74a?bypass=true
- https://www.kidoju.com/en/s/56fe803ad188a51a0090984a?bypass=true
- https://www.kidoju.com/en/s/56fe62cdd188a51a00909814?bypass=true

du français vers l'anglais : 
- https://www.kidoju.com/fr/s/570016f58e3e2f1d0072d8c8?bypass=true
- https://www.kidoju.com/fr/s/5702a574061edf1a002e2f1e?bypass=true
- https://www.kidoju.com/fr/s/5702c2049f59d91a00e7a1b4?bypass=true
- https://www.kidoju.com/fr/s/5701499f8e3e2f1d0072d9e2?bypass=true
- https://www.kidoju.com/fr/s/570149da8e3e2f1d0072d9ee?bypass=true
- https://www.kidoju.com/fr/s/57000b458e3e2f1d0072d895?bypass=true
- https://www.kidoju.com/fr/s/570149bc8e3e2f1d0072d9e6?bypass=true

Merci beaucoup pour votre aide !

**Comment by jlchereau** [comment]
C'est fait: veuillez bien tout vérifier car les mises à jour directement en database ne subissent aucun controle. Notez que la premiere et la derniere adresse de la première liste sont les mêmes.
