### ISSUE TITLE
Problème avec les connecteurs

### ISSUE THREAD

**Issue by ManonJ** [kidoju/Kidoju-Feedback#28]
Bonjour,
Je rencontre un problème avec l'utilisation des connecteurs, depuis une semaine environ.
Il s'agit du test logique : avant, on choisissait la solution dans un menu déroulant qui contenait toutes les valeurs. Maintenant, "Solution" s'affiche avec une case à remplir au lieu d'un menu déroulant. J'ai donc rentré à la main la valeur correspondant à la solution, mais quand on joue le quizz ça ne marche pas, les réponses sont toutes comptées fausses à la fin.

**Comment by jlchereau** [comment]
Voir https://github.com/kidoju/Kidoju-Feedback/issues/16#issuecomment-211243837

Vous pouvez tester l'exemple de la documentation à l'adresse https://www.kidoju.com/en/x/570cc7f46d1dd91900729417/570cc7f56d1dd91900729418#/9

**Comment by ManonJ** [comment]
Merci, maintenant c'est bon.
Cependant, je tiens à signaler que j'ai été obligée de revenir sur des quizz déjà faits pour modifier les connecteurs logiques selon cette nouvelle version. Il en est de même pour les cases à cocher : le principe du test logique a changé et je suis obligée de revenir sur des quizz déjà faits pour modifier les pages contenant des tests logiques de type case à cocher.
Il serait donc utile que ce type de modifications n'impacte pas les quizz déjà faits car sinon c'est une perte de temps.

**Comment by jlchereau** [comment]
Si je suis désolé de ce contretemps, ces deux modifications ont été faites suite aux très pertinentes objections de votre équipe et notre compréhension était que la note et la plume avait demandé de ne pas utiliser les connecteurs et checkboxes en attendant. Il ne devait donc pas y avoir d’impact. En tous cas, Merci.
