### ISSUE TITLE
probleme pour charger la page de jeu

### ISSUE THREAD

**Issue by noteplume** [kidoju/Kidoju-Feedback#29]
https://www.kidoju.com/fr/x/56ff91f38e3e2f1d0072d79b/56ff91f48e3e2f1d0072d79c
il faut relancer plusieurs fois avant que cette page ne s'affiche

**Comment by jlchereau** [comment]
C'est un problème d'infrastructure: "Gateway timeout". Je regarde.

![image](https://cloud.githubusercontent.com/assets/2556751/14737719/76974e20-0875-11e6-84dc-018e0c140250.png)

**Comment by jlchereau** [comment]
Il semble que le problème soit lié à un composant de l'infrastructure, appelé [NGINX](https://www.nginx.com/).

Conformément à https://www.scalescale.com/tips/nginx/504-gateway-time-out-using-nginx/ j'ai augmenté le timeout des connections. A suivre...

**Comment by jlchereau** [comment]
Le problème ne s'est pas répété.
