### ISSUE TITLE
non prise en compte de questions

### ISSUE THREAD

**Issue by noteplume** [kidoju/Kidoju-Feedback#33]
Pourquoi dans ce test, pour la slide 8, le tableau des scores ne prend en compte que 2 questions sur les 4?
https://www.kidoju.com/en/s/5717950b26c8b91900aef45c?bypass=true

**Comment by jlchereau** [comment]
Ce test n'est pas publié, je n'y ai donc pas accès sans le compte et le mot de passe.

**Comment by noteplume** [comment]
compte alexandre.kidoju@gmail.com 
code kidojualex

**Comment by jlchereau** [comment]
Je ne peux pas accéder à son compte car il a enregistré son téléphone pour le sécuriser.

![image](https://cloud.githubusercontent.com/assets/2556751/14890106/42ea8342-0d59-11e6-9866-87656ab03a52.png)

Je ferai un téléchargement de la base de données demain pour regarder. Du coup ce sera un peu plus long.

**Comment by jlchereau** [comment]
C'est corrigé.
