### ISSUE TITLE
Taille police par défaut

### ISSUE THREAD

**Issue by LouiseCNS** [kidoju/Kidoju-Feedback#34]
Bonjour, 

Serait-il possible de régler la taille de la police par défaut sur 60px au lieux de 80px ?
La taille 80px est trop élevée pour réaliser les slides, et iul faut donc la changer pour chaque case de texte.
Merci,

Louise

**Comment by jlchereau** [comment]
Je comprends que c'est pour les boites de texte ou textboxes (#12), pas pour les labels (#5).
C'est facile. Ce sera fait dans la prochaine version.

**Comment by jlchereau** [comment]
Après vérification, la taille de police sur les boites de texte est dynamique. Elle s'adapte automatiquement aux dimensions. La taille par défaut n'est pas 80px mais 65% de la hauteur. Parle-t-on de la même chose?

**Comment by LouiseCNS** [comment]
Ma question concernait l'outil label. Peut-on faire en sorte que la police soit de la même manière que pour les textbox adaptée à la taille du cadre ?

**Comment by LouiseCNS** [comment]
De même pour l'outil label, serait-il possible d'avoir un affichage comme pour l'outil explication ou instruction, de façon à voir la totalité du texte affiché dans une grande case, et non sur une seule petite ligne comme c'est le cas actuellement ? Ceci permettrait de corriger plus facilement d'éventuelles fautes d'orthographe.

**Comment by LouiseCNS** [comment]
De façon plus générale, l'idéal serait que comme pour l'outil textbox, les outils quizz et labels soient proportionnels à la taille du cadre : ceci éviterait les problèmes de positionnement des X et V de correction, ainsi que les changements permanents de police.

**Comment by jlchereau** [comment]
C'est en partie fait dans la version 0.1.8. Vous avez:
- les labels à 60px;
- l'édition dans une « textarea » au lieu d'une « textbox ».

Vous n'avez pas le redimensionnement automatique comme pour les textbox. Nous l'avions il y a plusieurs mois mais ça a été supprimé à la demande d’utilisateurs. Il ressort que la bonne solution est la taille fixe avec une barre d’outils de formatage comme dans PowerPoint. Nous y travaillons pour cet été.
