### ISSUE TITLE
Affichage des boutons de défilement et des tick et croix lors de la réalisation des quizz

### ISSUE THREAD

**Issue by LouiseCNS** [kidoju/Kidoju-Feedback#35]
Bonjour,

Il serait très utile d'afficher l'emplacement des boutons de défilement des questions et des X et V de corrections lors de la réalisation des quiz afin de positionner au mieux les cases, sans avoir à vérifier à chaque fois en jouant le quizz. Cela éviterait les chevauchements entre ces boutons et les images ou texte des quizz.

Merci d'avance,

Louise

**Comment by jlchereau** [comment]
Voir #23.

**Comment by LouiseCNS** [comment]
Qu'en est-il pour les flèches de défilement des questions ?

**Comment by noteplume** [comment]
c'est la même chose. Cela permettrait de tout positionner correctement lors de la rédaction des questions alors qu'actuellement, il faut passer par "jouer" et "correction" pour vérifier qu'il n'y a pas de chevauchement.

**Comment by jlchereau** [comment]
Je comprends le problème.

Pour les ticks et les croix, ca me parait difficile à afficher sous le bouton de dimensionnement des composants d'une page. Une fois que l'on sait que le tick est en dessous (grosso modo), c'est assez facile de dimensionner les composants pour afficher correctement les ticks et les croix. 

Pour les chevrons de défilement des questions, je ne pense pas qu'afficher des boutons qui ne servent à rien dans l'éditeur juste pour représenter leur emplacement soit une bonne solution. Cela fait quelques semaines que je songe à les déplacer (dans les coins inférieurs?) ou à ne les faire apparaitre qu'a certaines conditions. Je ne sais pas encore la bonne solution et je suis ouvert aux suggestions.

**Comment by jlchereau** [comment]
Première version de Facebook en 2004:

![image](https://cloud.githubusercontent.com/assets/2556751/14919492/0811c578-0e21-11e6-90b6-d4838d0fae92.png)

**Comment by LouiseCNS** [comment]
L'idéal serait d'afficher les boutons de défilement de part et d'autre de la diapo de quizz, et non sur le quizz. Cela serait-il possible ?

**Comment by jlchereau** [comment]
Ca ne marche pas car on offre la possibilité d'inclure des Quiz sur des pages web comme des videos YouTube. Afin d'optimiser l'espace, le `iframe` ne contient que la surface de la page (diapo).

![image](https://cloud.githubusercontent.com/assets/2556751/14924748/ecab1648-0e3b-11e6-8754-545d82c4e96a.png)

![image](https://cloud.githubusercontent.com/assets/2556751/14924886/7e282818-0e3c-11e6-8102-34f6f59ce0ec.png)
