### ISSUE TITLE
Flèches de défilement des questions

### ISSUE THREAD

**Issue by LouiseCNS** [kidoju/Kidoju-Feedback#36]
La taille des flèches de défilement des questions n'est pas fixe par rapport à la slide, elle dépend de la taille de la fenêtre et donc de l'écran de l'utilisateur. 
Les chevauchements entre le texte/images et ces flèches est donc variable d'un utilisateur à l'autre. 
Il serait judicieux de rendre la taille de ces flèches proportionnelle à la taille de la slide et non à la taille de la fenêtre du navigateur.

**Comment by jlchereau** [comment]
Je vous accorde que le positionnement des chevrons de navigation n'est pas idéal. Nous réfléchissons à plusieurs solutions qui font actuellement l'objet de discussions.

FYI , on a déjà essayé de les réduire proportionnellement à la taille de la page/slide mais ça devient rapidement petit en particulier sur les téléphones. Si on les réduit, il faut donc le faire selon une échelle différente de la page/slide ou avec un minimum. Il faut peut-être combiner cela avec un déplacement dans les coins inferieurs. Je ne suis pas encore certain. En tous cas, c’est dans la liste des choses à faire.

**Comment by jlchereau** [comment]
Now https://github.com/jlchereau/Kidoju-Webapp/issues/152.
