### ISSUE TITLE
Conservation des dimensions des images

### ISSUE THREAD

**Issue by LouiseCNS** [kidoju/Kidoju-Feedback#37]
Serait-il possible que les images insérées soient proportionnelles à l'image d'origine, et non au cadre dans lequel elles s'insèrent ?
De plus, il serait pratique que la dernière image téléchargée soit par défaut celle insérée, sans avoir à recliquer dessus une fois téléchargée.

**Comment by LouiseCNS** [comment]
De plus, serait-il possible de sélectionner plusieurs images au sein du même fichier lors de l'importation afin de pouvoir importer toutes les images du quizz d'un coup ?

**Comment by jlchereau** [comment]
Il y a 3 points:
1. Je vous accorde que le premier est pénible. On va regarder.
2. Le deuxième n'est pas un gros inconvénient mais on va regarder aussi.
3. Le troisième point est nettement plus compliqué. C'est déjà dans notre liste mais ça ne pourra pas être fait d'ici cet été.
