### ISSUE TITLE
Changement de taille de police

### ISSUE THREAD

**Issue by LouiseCNS** [kidoju/Kidoju-Feedback#38]
Pour les dropzone (et plus généralement l'ensemble des outils : label, QCM etc..., mais il me semble que le problème se pose uniquement pour dropzone), serait-il possible que la fontsize s'affiche par défaut quand on est face au "tableau" d'attributs d'affichage --> style.
Ceci éviterait de chercher fontsize au milieu de tous les autres outils de mise en page utilisés plus rarement.
De plus, la taille par défaut des police pour les outils QCM/dropdown et dropzone pourrait-elle être modifiée à 30px, et pour l'outil dropzone la largeur des tirets à 3px ?

Merci d'avance

**Comment by jlchereau** [comment]
Pour les QCM, la taille de police par défaut est la même pour tous les modes: radio, bouton et dropdown. Le changemnt affecte nécessairement les trois.

Pour les dropzone, c'est déjà fait. Ce sera dans la prochaine version probablement déployée ce week-end.
