### ISSUE TITLE
Alignement des dropzone, des images, des labels et des connecteurs...

### ISSUE THREAD

**Issue by LouiseCNS** [kidoju/Kidoju-Feedback#39]
Il est actuellement très difficile d'aligner les différents cadres générés, en particulier quand on a affaire à des tests nécessitant un nombre important de cadres (connecteurs et dropzone notamment).
Serait-il possible d'avoir un alignement semi-automatique ou facilité ?

**Comment by jlchereau** [comment]
Voir les nouvelles fonctions d'alignement pour établir une grille, les composants s'alignant automatiquement sur la grille.

![image](https://cloud.githubusercontent.com/assets/2556751/15701180/a65ba618-27d0-11e6-9d00-98887dc9feb2.png)
