### ISSUE TITLE
Duplication des outils au sein d'une slide

### ISSUE THREAD

**Issue by LouiseCNS** [kidoju/Kidoju-Feedback#40]
Il serait très utile de pouvoir dupliquer au sein de la même slide les différents outils en gardant le style (taille, police, couleur...), notamment pour les labels.

**Comment by jlchereau** [comment]
C'est déjà fait. Ce sera dans la prochaine version probablement déployée ce week-end.

![image](https://cloud.githubusercontent.com/assets/2556751/15293514/44afaf10-1b80-11e6-8bca-f59c213a962b.png)
