### ISSUE TITLE
Correction et description

### ISSUE THREAD

**Issue by LouiseCNS** [kidoju/Kidoju-Feedback#41]
Afin de faciliter la correction, la partie description d'un test logique au sein d'une slide pourrait-elle prendre par défaut le contenu du label en haut de la slide (qui en général contient la question posée) ?

**Comment by jlchereau** [comment]
Ca me parait une bonne idée, mais je ne suis pas certain de la manière de la réaliser:

Quelle est votre suggestion quand il y a plusieurs labels sur la page?
Quelle est votre suggestion quand il y a plusieurs questions sur la page?
Que se passe-t-il quand on change/corrige le label?
Que se passe-t-il quand on supprime le label?
Que se passe-t-il quand apres avoir supprimé le label on rajoute le label?
Que se passe-t-il si on a mis une description spécifique (non liée à aucun label) dans les cas ci-dessus?

On ne peut pas lier le label et la description de manière automatique. Le mieux que l'on puisse faire est de proposer.

J'ai l'impression que la bonne manière de le faire est de remplacer la textbox de description par une [combobox](http://demos.telerik.com/kendo-ui/combobox/index) qui contiendrait tous les labels de la page. Il y aurait juste a sélectionner un label dans la partie liste déroulante ou à entrer sa description spécifique dans la partie textbox.

Si cela vous semble bien, ca doit pouvoir se faire.

**Comment by LouiseCNS** [comment]
La combobox telle que décrite me paraît une très bonne solution, surtout si l'on peut toujours rentrer une description spécifique.

**Comment by jlchereau** [comment]
C'est fait. Ce sera dans la prochaine version déployée ce week-end.

![image](https://cloud.githubusercontent.com/assets/2556751/15293561/764c325a-1b80-11e6-8763-91aadf17c483.png)
