### ISSUE TITLE
Explications obligatoires dans la console

### ISSUE THREAD

**Issue by LouiseCNS** [kidoju/Kidoju-Feedback#42]
Certaines questions ne se prêtent pas à des explications, tandis que d'autres s'y prêtent (par exemple pour des questions de vocabulaire : le mot ou l'expression choisi est soit juste soit faux...).
Le critère de publication de la console basé sur la présence d'une explication pour chaque slide paraît trop strict. Les explications pourraient plutôt être recommandées.

**Comment by jlchereau** [comment]
Dans le cas cité, ne serait-il pas intéressant d'avoir la définition du mot, l'idée étant aussi d'apprendre quelque chose de ces QUIZ? Juste savoir que l'on a bon au faux n'est pas très excitant.

Voir https://www.kidoju.com/fr/x/56d6ef08bc039c1a00062952/56d6ef08bc039c1a00062953

Ce que j'ai fait dans ce quiz est de copier les trois premières lignes de Wikipedia sous licence Creative Common. Notez que les explications supportent [Markdown](https://github.com/kidoju/Kidoju-Feedback/issues/14).
