### ISSUE TITLE
Problème d'upload des photos

### ISSUE THREAD

**Issue by LouiseCNS** [kidoju/Kidoju-Feedback#44]
Bonjour,

Au moment d'uploader les photos, après les avoir sélectionné et appuyé sur ouvrir dans l'explorateur de fichiers, les photos ne se chargent pas sur l'interface (qui semble complètement inactive).
Ce problème et récurrent et indépendant de l'utilisateur. En revanche les images déjà présentes sur le quizz s'affichent bien.

Merci

**Comment by jlchereau** [comment]
C'est déja identifié et résolu dans la mise à jour de ce soir.
