### ISSUE TITLE
Erreur de calcul du score/problème de sauvegarde

### ISSUE THREAD

**Issue by LouiseCNS** [kidoju/Kidoju-Feedback#47]
J'ai fréquemment des erreurs de sauvegarde des modifications apportées aux quizz sans pouvoir en identifier la cause.
D'autre part, quand je lance les quizz fini, une fois les réponses apportées, j'ai "erreur de calcul du score" et impossible d'identifier la source du problème, et ceci sur différents quizz.

**Comment by jlchereau** [comment]
Avec la meilleure bonne volonté du monde, que voulez-vous que je fasse de cela?

Vous ne donnez aucune information qui me permette de reproduire le problème que vous invoquez à commencer par la référence du Quiz qui pose problème et le navigateur utilisé car sans l'un et l'autre je ne peux rien faire.

Ensuite, quelles sont les circonstances?
- est-ce que le probleme concerne toujours le meme Quiz?
- est-ce en début de session ou apres avoir travaillé longtemps dans le logiciel?
- quand un Save échoue, est-ce que le Save suivant réussit?
- etc.

Le Save est testé par des procedures automatiques et il fonctionne. Je ne doute pas que vous expérimentiez un probleme, mais il releve nécessairement de conditions ou d'un environnement particulier (browser non testé, mauvaise connexion wifi, etc.).

On fait des tests tres poussés dans la derniere version de Google Chrome, moins dans les dernieres versions de Firefox, Internet Explorer et Safari, et pas du tout dans les autres browsers ou versions anciennes.

**Comment by LouiseCNS** [comment]
est-ce que le probleme concerne toujours le meme Quiz? Oui, sur plusieurs quizz 
https://www.kidoju.com/en/x/56fd373fd188a51a009097e5/56fd3740d188a51a009097e6#/3
https://www.kidoju.com/en/s/56fd26ded188a51a009097c3
https://www.kidoju.com/en/x/56fc0503d188a51a00909737/56fc0503d188a51a00909738#/2

est-ce en début de session ou apres avoir travaillé longtemps dans le logiciel? après avoir travaillé longuement sur le logiciel, mais le problème réapparait quand on se relogue sur le site.
quand un Save échoue, est-ce que le Save suivant réussit? Oui, mais sans avoir pris en compte les modifications réalisées, il faut donc tout refaire.

J'utilise Firefox. Ce n'est pas un problème de connexion wifi (ou alors hyper ponctuel).

**Comment by LouiseCNS** [comment]
Le problème semble concerner tous les quizz.

**Comment by jlchereau** [comment]
### Sauvegarde

En ce qui concerne la sauvegarde apres une longue session je vous recommande de sauver souvent en attendant que l'on trouve le problème. Si vous sauvez souvent, ca ne devrait pas etre bloquant.

Je ne vois qu'une raison pour laquelle cela puisse se passer d'autant que nous n'avons pas de procédure de test automatique de cette fonctionnalité à cause du delai d'attente. Les tokens d'autorisation délivrés par Google ont un validité d'une heure. Ces tokens sont ensuite passés par le browser avec chaque requete. Il pourrait y avoir un probleme avec le renouvellement du token dans votre environnement, ce qui ferait qu'apres une session d'une heure, la sauvegarde ne serait pas autorisée. Mais dans ce cas vous ne devriez pas pouvoir sauvegarder ensuite. **Pouvez-vous me confirmer que vous pouvez sauvegarder sans avoir à vous re-identifier?**

### Calcul des scores

J'ai executé plusieurs tests avec la derniere version de Firefox sous windows et osx sans problème. **Quelle version de Firefox sur quel ordinateur utilisez-vous?** La version de Firefox que vous utilisez doit [supporter les "web workers"](http://caniuse.com/#feat=webworkers) et votre ordinateur doit etre suffisammenet rapide pour que chaque validation se fasse en moins de 50ms. Cette limite peut etre changée mais c'est une mesure de sécurité pour éviter que des hackers ne créent des scripts malveillants donc plus on la monte, plus on s'expose.

![image](https://cloud.githubusercontent.com/assets/2556751/16517420/331fb588-3f75-11e6-9df3-117ce396b717.png)

![image](https://cloud.githubusercontent.com/assets/2556751/16526112/8743c118-3fa7-11e6-8559-d552328a3c7b.png)
